# Generated by Django 4.0 on 2021-12-15 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название игры')),
                ('is_cost_limit', models.BooleanField(verbose_name='Будут ли лимиты?')),
                ('cost_limit', models.CharField(max_length=40, verbose_name='Лимит на стоимость')),
                ('reg_finish', models.DateTimeField(verbose_name='Дата окончания регистраций')),
                ('delivery', models.DateTimeField(verbose_name='Дата отправления подарока')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создана игра')),
            ],
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td_id', models.CharField(max_length=20, verbose_name='ID телеграмма')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ?')),
                ('name', models.CharField(max_length=200, verbose_name='Имя игрока')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер владельца')),
                ('letter', models.TextField(verbose_name='Письмо Санте')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.games', verbose_name='Игра')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Зона интереса для подарка')),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='who', to='bot.gameuser', verbose_name='Кто дарит')),
                ('whom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whom', to='bot.gameuser', verbose_name='Кому дарит')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подарка')),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='interest',
            field=models.ManyToManyField(to='bot.Interest', verbose_name='Интересы игрока'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='wishlist',
            field=models.ManyToManyField(to='bot.Wishlist', verbose_name='Вишлист игрока'),
        ),
    ]
