# Generated by Django 4.0 on 2021-12-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_games_gameuser_interest_lottery_wishlist_delete_game_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
