# Generated by Django 4.0 on 2021-12-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_games_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_cost_limit',
        ),
        migrations.AlterField(
            model_name='game',
            name='cost_limit',
            field=models.CharField(blank=True, max_length=40, verbose_name='Лимит на стоимость'),
        ),
    ]
