# Generated by Django 4.0 on 2021-12-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_game_is_cost_limit_alter_game_cost_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='gameuser',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Интерес', 'verbose_name_plural': 'Интересы'},
        ),
        migrations.AlterModelOptions(
            name='lottery',
            options={'verbose_name': 'Жеребьевка', 'verbose_name_plural': 'Жеребьевки'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Вишлист', 'verbose_name_plural': 'Вишлисты'},
        ),
        migrations.AlterField(
            model_name='game',
            name='delivery',
            field=models.DateTimeField(verbose_name='Дата отправления подарка'),
        ),
        migrations.RemoveField(
            model_name='gameuser',
            name='game',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='game',
            field=models.ManyToManyField(to='bot.Game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='interest',
            field=models.ManyToManyField(blank=True, to='bot.Interest', verbose_name='Интересы игрока'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='bot.Wishlist', verbose_name='Вишлист игрока'),
        ),
    ]
