# Generated by Django 4.0 on 2021-12-16 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_gameuser_letter_alter_gameuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.game', verbose_name='Игра'),
        ),
    ]
