# Generated by Django 4.0 on 2021-12-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_lottery_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код игры'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='username',
            field=models.CharField(blank=True, max_length=40, verbose_name='Юзернейм игрока'),
        ),
    ]
