# Generated by Django 4.0 on 2021-12-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_game_code_gameuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название подарка')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на картинку')),
                ('price', models.PositiveIntegerField(blank=True, max_length=100, null=True, verbose_name='Цена (целое число)')),
            ],
            options={
                'verbose_name': 'Подарок',
                'verbose_name_plural': 'Подарки',
            },
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Название категории', 'verbose_name_plural': 'Названия категорий'},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.wishlistitem', verbose_name='Подарки'),
        ),
    ]
