# Generated by Django 4.0 on 2021-12-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_wishlistitem_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='item',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='bot.WishlistItem', verbose_name='Подарки'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена (целое число)'),
        ),
    ]
