# Generated by Django 4.0 on 2021-12-17 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_remove_wishlist_item_wishlist_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Вишлист', 'verbose_name_plural': 'Вишлисты'},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='item',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на картинку'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.interest', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена подарка'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория для подарка'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название подарка'),
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
