# Generated by Django 4.0 on 2021-12-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_wishlist_options_remove_wishlist_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='game',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='p',
            field=models.ManyToManyField(to='bot.Game', verbose_name='Игра'),
        ),
    ]
