# Generated by Django 4.0 on 2021-12-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_gameuser_interest_raw_gameuser_wishlist_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tg_id_owner',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
