# Generated by Django 4.0 on 2021-12-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_remove_gameuser_game_gameuser_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameuser',
            old_name='p',
            new_name='game',
        ),
    ]
