# Generated by Django 4.0 on 2021-12-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_game_tg_id_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tg_id_owner',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID владельца'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='game',
            field=models.ManyToManyField(related_name='players', to='bot.Game', verbose_name='Игра'),
        ),
    ]
