# Generated by Django 4.0 on 2021-12-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_game_tg_id_owner_alter_gameuser_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lottery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения лотереи'),
        ),
    ]
